{% set name = "bodo" %}
{% set version = "2025.7.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/bodo-ai/Bodo/archive/refs/tags/{{ version }}.tar.gz
  sha256: 5f2e8f1d92d84c9ac9ca56348e29a4996b8c42b347f88334fbda4ab3a98eabeb
  patches:
    - patches/0001-fix-cross-compile.patch

build:
  skip: true  # [py<310]
  number: 2
  rpaths:
    - lib
    - {{ PREFIX }}/lib
    - {{ SP_DIR }}/pyarrow
  missing_dso_whitelist:
    - '*/arrow_python.dll'   # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake <4.0,>=3.23
    - ninja
    - cross-python_{{ target_platform }}    # [build_platform != target_platform]
    - python                                # [build_platform != target_platform]
    - cython >=3.0                          # [build_platform != target_platform]
    - numpy                                 # [build_platform != target_platform]
    - pyarrow-core                          # [build_platform != target_platform]

  host:
    - python
    - pip

    # Build Deps
    - setuptools >=64
    - cython >=3.0
    - setuptools_scm >=8
    - scikit-build-core
    - mpi4py >=4.0,<4.1

    # Arrow Deps
    - libarrow
    - libarrow-dataset
    - libparquet
    - pyarrow-core

    # C++ Deps
    - libboost-headers  # [not win]
    - libboost-devel    # [win]
    - aws-sdk-cpp
    - zstd
    - hdf5 * mpi_mpich_*  # [not win]
    - hdf5 * *mpi_impi_*  # [win]
    - h5py

    # Resricting mpich to prevent hangs on MacOS when using MPI Spawn.
    - mpich <4.2            # [not win]

    # Python Deps
    - numba =0.61.2
    - numpy
    - impi-devel            # [win64]

  run:
    - python
    - numpy >=1.24
    - pandas >=2.2
    - pyarrow-core
    - pyarrow
    - fsspec >=2021.09
    - numba =0.61.2
    - mpich <4.2            # [not win]
    - requests
    - openssl               # [win]
    - zstd
    - cloudpickle >=3.0
    - psutil

  # run_constrained means these packages are not required deps
  # but will restrict them if they are present in the conda env.
  run_constrained:
    - s3fs >=2022.1.0
    - adlfs >=2022.1.0
    - pyiceberg >=0.9

test:
  imports:
    - bodo
  source_files:
    - examples/Misc/misc_pi.py

about:
  home: https://bodo.ai
  license: Apache-2.0
  license_file: LICENSE
  summary: High-Performance Python Compute Engine for Data and AI

extra:
  recipe-maintainers:
    - ehsantn
    - IsaacWarren
    - hadia206
    - knassre-bodo
    - scott-routledge2
    - DrTodd13
