{% set name = "bodo" %}
{% set version = "2025.10.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/bodo-ai/Bodo/archive/refs/tags/{{ version }}.zip
  sha256: 3c0df3b4f14923f42eff6c7b56c37150c4d82d0a09efc88708935ff13f30a140

build:
  skip: true  # [py<39]
  number: 0
  rpaths:
    - lib
    - {{ PREFIX }}/lib
    - {{ SP_DIR }}/pyarrow
  missing_dso_whitelist:
    - '*/arrow_python.dll'   # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake <4.0,>=3.23
    - ninja
    - cross-python_{{ target_platform }}    # [build_platform != target_platform]
    - python                                # [build_platform != target_platform]
    - cython >=3.0                          # [build_platform != target_platform]
    # Restricting numpy in build for compatibility with numba requirements.
    - numpy <2.3                            # [build_platform != target_platform]
    - libarrow                              # [build_platform != target_platform]
    - pyarrow-core                          # [build_platform != target_platform]

  host:
    - python
    - pip

    # Build Deps
    - setuptools >=64
    - cython >=3.0
    - setuptools_scm >=8
    - scikit-build-core
    - mpi4py >=4.0,<4.1

    # Arrow Deps
    - libarrow
    - libarrow-dataset
    - libparquet
    - pyarrow-core

    # C++ Deps
    - libboost-headers  # [not win]
    - libboost-devel    # [win]
    - aws-sdk-cpp
    - zstd
    - hdf5 * mpi_mpich_*  # [not win]
    - hdf5 * *mpi_impi_*  # [win]
    - h5py

    # Resricting mpich to prevent hangs on MacOS when using MPI Spawn.
    - mpich <4.2            # [not win]

    # Python Deps
    # Bodo requires numba <0.62 due to known issues with numba 0.62.0
    - numba >=0.60,<0.62
    - numpy
    - impi-devel            # [win64]

  run:
    - python
    - numpy >=1.24
    - pandas >=2.2
    - pyarrow-core
    - pyarrow
    - fsspec >=2021.09
    - numba >=0.60,<0.62
    - mpich <4.2            # [not win]
    - requests
    - openssl
    - zstd
    - cloudpickle >=3.0
    - psutil

  # run_constrained means these packages are not required deps
  # but will restrict them if they are present in the conda env.
  run_constrained:
    - s3fs >=2022.1.0
    - adlfs >=2022.1.0
    - pyiceberg >=0.9

test:
  imports:
    - bodo
  source_files:
    - examples/Misc/misc_pi.py

about:
  home: https://bodo.ai
  license: Apache-2.0
  license_file: LICENSE
  summary: High-Performance Python Compute Engine for Data and AI

extra:
  recipe-maintainers:
    - ehsantn
    - IsaacWarren
    - hadia206
    - knassre-bodo
    - scott-routledge2
    - DrTodd13
