{% set name = "bodo" %}
{% set version = "2025.5" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/bodo-ai/Bodo/archive/refs/tags/{{ version }}.tar.gz
  sha256: 879370fd33c7c2f4f3255076eabbc875f43bde6d4a189847b0fbc011821b2899
  patches:
    - patches/0001-fix-boost-cmake.patch

build:
  skip: True  # [py<310]
  number: 0
  rpaths:
    - lib
    - {{ PREFIX }}/lib
    - {{ SP_DIR }}/pyarrow
  missing_dso_whitelist:
    - '*/arrow_python.dll'   # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake <4.0,>=3.23
    - ninja
    - cross-python_{{ target_platform }}    # [build_platform != target_platform]
    - python                                # [build_platform != target_platform]
    - cython ~=3.0                          # [build_platform != target_platform]
    - numpy                                 # [build_platform != target_platform]

  host:
    - python
    - pip

    # Build Deps
    - setuptools >=64
    - cython ~=3.0
    - setuptools_scm >=8
    - scikit-build-core
    - mpi4py ~=4.0

    # Arrow Deps
    - libarrow =19.0.0
    - libarrow-dataset =19.0.0
    - libparquet =19.0.0
    - pyarrow-core =19.0.0

    # C++ Deps
    - libboost-headers =1.85  # [not win]
    - libboost-devel =1.85    # [win]
    - aws-sdk-cpp <=1.11.485
    - zstd <=1.5.6
    - hdf5 >=1.14.3,<1.14.4.0a0=mpi_mpich_*  # [not win]
    - hdf5 >=1.14.3,<1.14.4.0a0=*mpi_impi_*  # [win]

    # Python Deps
    - numba =0.61.2
    # Compatible with Numba requirements
    - numpy >=1.24
    - pandas >=2.2,<2.3
    - fsspec >=2021.09
    - h5py
    - mpich 4.1.*=h*        # [not win]
    - impi-devel            # [win64]
    - requests
    - cloudpickle >=3.0,<4.0

  run:
    - python
    - {{ pin_compatible('numpy') }}
    - pandas >=2.2,<2.3
    - pyarrow-core =19.0.0
    - pyarrow =19.0.0
    - fsspec >=2021.09
    - numba 0.61.2
    - mpich *=h*  # [not win]
    - requests
    - openssl     # [win]
    - zstd <=1.5.6
    - cloudpickle >=3.0,<4.0
    - psutil

  # run_constrained means these packages are not required deps
  # but will restrict them if they are present in the conda env.
  run_constrained:
    - numpy >=1.24
    - scikit-learn =1.4.*
    - s3fs >=2022.1.0
    - adlfs >=2022.1.0
    - pyiceberg >=0.9,<0.10
    - boto3 *
    - mypy-boto3-glue *

test:
  imports:
    - bodo
  source_files:
    - examples/Misc/misc_pi.py

about:
  home: https://bodo.ai
  license: Apache-2.0
  license_file: LICENSE
  summary: High-Performance Python Compute Engine for Data and AI

extra:
  recipe-maintainers:
    - ehsantn
    - IsaacWarren
    - hadia206
    - knassre-bodo
    - scott-routledge2
    - DrTodd13
